AWSTemplateFormatVersion: 2010-09-09
Description: SageMaker environment

Parameters:
  EnvPrefix:
    Description: "Input Environment Prefix"
    Type: String
    Default: "mlenv"

  VpcCidrBlock:
    Description: "Input VPC CIDR Block"
    Type: String
    Default: "10.100.0.0/22"

  SubnetAzACidrBlock:
    Description: "Input AZ-A Subnet CIDR Block"
    Type: String
    Default: "10.100.0.0/28"

  SubnetAzCCidrBlock:
    Description: "Input AZ-C Subnet CIDR Block"
    Type: String
    Default: "10.100.0.16/28"

Mappings:
  # Refer to: https://docs.aws.amazon.com/ja_jp/sagemaker/latest/dg/notebooks-available-images.html
  SageMakerDistImgNumNumMap:
    us-east-1:
      ImageNumber: "885854791233"
    us-east-2:
      ImageNumber: "137914896644"
    us-west-1:
      ImageNumber: "053634841547"
    us-west-2:
      ImageNumber: "542918446943"
    af-south-1:
      ImageNumber: "238384257742"
    ap-east-1:
      ImageNumber: "523751269255"
    ap-south-1:
      ImageNumber: "245090515133"
    ap-northeast-1:
      ImageNumber: "010972774902"
    ap-northeast-2:
      ImageNumber: "064688005998"
    ap-northeast-3:
      ImageNumber: "564864627153"
    ap-southeast-1:
      ImageNumber: "022667117163"
    ap-southeast-2:
      ImageNumber: "648430277019"
    ap-southeast-3:
      ImageNumber: "564864627153"
    ca-central-1:
      ImageNumber: "481561238223"
    eu-central-1:
      ImageNumber: "545423591354"
    eu-west-1:
      ImageNumber: "819792524951"
    eu-west-2:
      ImageNumber: "021081402939"
    eu-west-3:
      ImageNumber: "856416204555"
    eu-north-1:
      ImageNumber: "175620155138"
    eu-south-1:
      ImageNumber: "810671768855"
    sa-east-1:
      ImageNumber: "567556641782"
    me-south-1:
      ImageNumber: "523774347010"
    me-central-1:
      ImageNumber: "358593528301"

Resources:
  ############################################
  ### SageMaker Studio
  ############################################
  SageMakerStudioDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      DomainName: !Sub "${EnvPrefix}-sagemaker-domain"
      AppNetworkAccessType: PublicInternetOnly
      AuthMode: IAM
      VpcId: !Ref Vpc
      SubnetIds:
        - !Ref SubnetAzA
        - !Ref SubnetAzC
      DefaultUserSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
        StudioWebPortal: ENABLED
        DefaultLandingUri: "studio::"
      DefaultSpaceSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
        JupyterLabAppSettings:
          LifecycleConfigArns:
            - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:studio-lifecycle-config/jupyter-lab-auto-stop-idle"

  SageMakerStudioUserProfile:
    Type: AWS::SageMaker::UserProfile
    Properties:
      DomainId: !Ref SageMakerStudioDomain
      UserProfileName: !Sub "${EnvPrefix}-sagemaker-user-profile"
      UserSettings:
        DefaultLandingUri: "studio::"
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn

  JupyterLabSpace:
    Type: AWS::SageMaker::Space
    Properties:
      DomainId: !Ref SageMakerStudioDomain
      SpaceName: !Sub "${EnvPrefix}-jupyterlab-space"
      SpaceDisplayName: "JupyterLab"
      OwnershipSettings:
        OwnerUserProfileName: !Sub "${EnvPrefix}-sagemaker-user-profile"
      SpaceSharingSettings:
        SharingType: Private
      SpaceSettings:
        AppType: JupyterLab
        JupyterLabAppSettings:
          DefaultResourceSpec:
            InstanceType: "ml.t3.medium"
            SageMakerImageVersionArn: !Sub
              - "arn:aws:sagemaker:${AWS::Region}:${SageMakerDistImgNum}:image-version/sagemaker-distribution-cpu/1"
              - { SageMakerDistImgNum: !FindInMap [SageMakerDistImgNumNumMap, !Ref AWS::Region, ImageNumber] }
        SpaceStorageSettings:
          EbsStorageSettings:
            EbsVolumeSizeInGb: 5

  ############################################
  ### Network
  ############################################
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvPrefix}-vpc"

  SubnetAzA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, Fn::GetAZs: !Ref "AWS::Region"] # AC-A
      CidrBlock: !Ref SubnetAzACidrBlock
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub "${EnvPrefix}-subnet-az-a"

  SubnetAzC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, Fn::GetAZs: !Ref "AWS::Region"] # AZ-C
      CidrBlock: !Ref SubnetAzCCidrBlock
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub "${EnvPrefix}-subnet-az-c"

  ############################################
  ### IAM
  ############################################
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvPrefix}-sagemaker-execution-role"
      Description: "Role for SageMaker execution"
      Policies:
        - PolicyName: iam-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:GetRolePolicy
                Resource: "*"
        - PolicyName: pass-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "arn:aws:iam::*:role/*"
                Condition:
                  StringLike:
                    iam:PassedToService:
                      - sagemaker.amazonaws.com
                      - events.amazonaws.com
        - PolicyName: kms-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:CreateKey
                  - kms:Get*
                  - kms:List*
                Resource: "*"
        - PolicyName: list-tags
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:ListTags
                Resource: "*"
        - PolicyName: get-service-quotas
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - servicequotas:GetServiceQuota
                Resource: !Sub "arn:${AWS::Partition}:servicequotas:${AWS::Region}:${AWS::AccountId}:sagemaker/*"
        - PolicyName: headless-execution-permissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - events:TagResource
                  - events:DeleteRule
                  - events:PutTargets
                  - events:DescribeRule
                  - events:PutRule
                  - events:RemoveTargets
                  - events:DisableRule
                  - events:EnableRule
                Resource: "*"
                Condition:
                  StringEquals:
                    "aws:ResourceTag/sagemaker:is-scheduling-notebook-job": "true"
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:PutBucketVersioning
                  - s3:PutEncryptionConfiguration
                Resource: "arn:aws:s3:::sagemaker-automated-execution-*"
              - Effect: Allow
                Action:
                  - sagemaker:AddTags
                Resource:
                  - "arn:aws:sagemaker:*:*:training-job/*"
                  - "arn:aws:sagemaker:*:*:pipeline/*"
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:CreateNetworkInterfacePermission
                  - ec2:CreateVpcEndpoint
                  - ec2:DeleteNetworkInterface
                  - ec2:DeleteNetworkInterfacePermission
                  - ec2:DescribeDhcpOptions
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeRouteTables
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeVpcs
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                  - ecr:GetAuthorizationToken
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:GetEncryptionConfiguration
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObject
                  - sagemaker:DescribeDomain
                  - sagemaker:DescribeUserProfile
                  - sagemaker:DescribeSpace
                  - sagemaker:DescribeStudioLifecycleConfig
                  - sagemaker:DescribeImageVersion
                  - sagemaker:DescribeAppImageConfig
                  - sagemaker:CreateTrainingJob
                  - sagemaker:DescribeTrainingJob
                  - sagemaker:StopTrainingJob
                  - sagemaker:Search
                  - sagemaker:CreatePipeline
                  - sagemaker:DescribePipeline
                  - sagemaker:DeletePipeline
                  - sagemaker:StartPipelineExecution
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
                - events.amazonaws.com
                - forecast.amazonaws.com
            Action:
              - sts:AssumeRole
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AWSCloudFormationFullAccess"
        - "arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSageMakerPipelinesIntegrations"
